import pandas as pd
import os

# Sample data structure based on the user's JSON
data = [
    {
        "nama": "naufal",
        "soal": "She decided to leave early to catch the sunrise.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "I hope to see you at the party later.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "She enjoys relaxing on weekends.",
        "infinitive_requirement": True,
        "gerund_requirement": False,
        "gerund_phrase_requirement": True,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 0
    },
    {
        "nama": "naufal",
        "soal": "They discussed moving to a new location.",
        "infinitive_requirement": True,
        "gerund_requirement": False,
        "gerund_phrase_requirement": True,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "He is looking forward to visiting his family.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "They are interested in learning more about it.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "She had received the message by the time we called her.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "They flew away before the storm hit.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "The person who called you is waiting outside.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": True,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "The book which you lent me was fascinating.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": True,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "There is too much sugar in this recipe.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "We need to buy more furniture for the office.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "If it rains, we will cancel the picnic.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": True,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "If she leaves early, she will catch the train.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": True,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "This gift is from me to him.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "She is sitting next to them.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "It is essential that he arrive on time.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 0
    },
    {
        "nama": "naufal",
        "soal": "The teacher recommends that she study more often.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "He agreed to accept the terms of the contract.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 0
    },
    {
        "nama": "naufal",
        "soal": "We plan to leave early to avoid traffic.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "Avoid sharing personal information online.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "She mentioned going to the new movie theater.",
        "infinitive_requirement": True,
        "gerund_requirement": False,
        "gerund_phrase_requirement": True,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "We are committed to making a difference in the community.",
        "infinitive_requirement": True,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 0
    },
    {
        "nama": "naufal",
        "soal": "She avoided talking about the issue directly.",
        "infinitive_requirement": True,
        "gerund_requirement": False,
        "gerund_phrase_requirement": True,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "He had locked his keys in the car yesterday.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "They moved to the new house last month.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "The scientist whose discovery changed the field was awarded a Nobel Prize.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": True,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "That is the reason that she decided to quit.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": True,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "Information is crucial for making informed decisions.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "The equipment has been updated to the latest technology.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": False,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "It is essential that every student follow the instructions carefully before starting the experiment.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": True,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "The contract stipulates that the tenant keep the property in good condition.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "It is vital that he go to the doctor as soon as possible.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "She suggested that Mary come with them to the meeting.",
        "infinitive_requirement": False,
        "gerund_requirement": True,
        "gerund_phrase_requirement": False,
        "irregular_past_form": True,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": True,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 1
    },
    {
        "nama": "naufal",
        "soal": "The doctor recommended that he drink more water to improve his health.",
        "infinitive_requirement": False,
        "gerund_requirement": False,
        "gerund_phrase_requirement": False,
        "irregular_past_form": False,
        "past_participle": False,
        "relative_pronouns": False,
        "singular_expression": False,
        "plural_expression": False,
        "factual_conditional": False,
        "importance_subjunctive_verb": True,
        "result": 0
    }
]

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(data)

# Export the DataFrame to an Excel file
path = os.getcwd()
filename = "competencies"
suffix = ".xlsx"
excel_path = path + "/data/" + filename + suffix
df.to_excel(excel_path, index=False)

excel_path