from src.models.question_bank import QuestionBank;
from src.models.test_result import TestResult;
from src.models.test_result_detail import TestResultDetail;
from src.models.user import User;
from src.utils.response import CustomResponse

# import render template
from flask import render_template, jsonify

class Recommendation():
    def __init__(self, user):
        self.user = user
    def HelloWord():
        return "hello word"
    
    # get recommendation
    @staticmethod
    def recommendation(id):
       # get user by id 
       user = User.get_by_id(id)
       # check if user exist or not
       if user is None:
            return CustomResponse.failure("user not found", 404)
       
       res = {
            "name": user.name,
            "recommendations": [
                "pronoun",
                "adj"
            ],
            "text": "generated by AI"
        }
       return CustomResponse.success(res)
    
    def getUser(self):
        return self.user